;; Configuration for Wifi with SQLite

[DatabaseService]
    StorageProvider = "OpenSim.Data.SQLite.dll"

[OfflineIM]
    StorageProvider = "OpenSim.Data.SQLite.dll"

[Groups]
    ; Wifi Groups need Diva.Data provider
    ; If Groups are disabled in OpenSim, Wifi will still try to load this for its internal services
    ; Using Diva.Data.SQLite for Groups compatibility with Wifi
    StorageProvider = "Diva.Data.SQLite.dll"

[WifiService]
    ; Wifi service still uses Diva.Data for extended features
    StorageProvider = "Diva.Data.SQLite.dll"