;; Configuration for Wifi with SQLite

[DatabaseService]
    StorageProvider = "Diva.Data.SQLite.dll"

[OfflineIM]
    StorageProvider = "Diva.Data.SQLite.dll"

[Groups]
    StorageProvider = "Diva.Data.SQLite.dll"

[WifiService]
    StorageProvider = "Diva.Data.SQLite.dll"