; This is the main configuration file for an instance of OpenSim running in standalone mode

[DatabaseService]
    ;
    ; ### Choose the DB
    ;

    ; SQLite
    Include-Storage = "config-include/storage/SQLiteStandalone.ini";

    ; MySQL
    ; Uncomment these lines if you want to use MySQL storage
    ; Change the connection string to your db details
    ; Remove SslMode=None if you need secure connection to the local MySQL
    ; In most cases ssl is just a pure waste of resources, specially when MySQL is on same machine, and closed to outside
    ; If using MySQL 8.0.4 or later, check that default-authentication-plugin=mysql_native_password
    ;   rather than caching_sha2_password is set in /etc/mysql/mysql.conf.d/mysqld.cnf (not applicable to MariaDB).
    ;StorageProvider = "OpenSim.Data.MySQL.dll"
    ;ConnectionString = "Data Source=localhost;Database=opensim;User ID=opensim;Password=***;Old Guids=true;SslMode=None;"

    ; Uncomment this line if you are using MySQL and want to use a different database for estates.
    ; The usual application for this is to allow estates to be spread out across multiple simulators by share the same database.
    ; Most people won't need to do this so only uncomment if you know what you're doing.
    ;EstateConnectionString = "Data Source=localhost;Database=opensim;User ID=opensim;Password=***;Old Guids=true;SslMode=None;"

    ; MSSQL
    ; Uncomment these lines if you want to use MSSQL storage
    ; Change the connection string to your db details
    ; The value for server property is shown in your SQL Server Management Studio login dialog.
    ; (This sample is the default of express edition)
    ;StorageProvider = "OpenSim.Data.MSSQL.dll"
    ;ConnectionString = "Server=localhost\SQLEXPRESS;Database=opensim;User Id=opensim; password=***;"

    ; PGSQL
    ; Uncomment these lines if you want to use PGSQL storage
    ; Change the connection string to your db details
    ;StorageProvider = "OpenSim.Data.PGSQL.dll"
    ;ConnectionString = "Server=localhost;Database=opensim;User Id=opensim; password=***;SSL Mode = Disable"

[Hypergrid]
    ; Uncomment the variable GatekeeperURI to enable 
    ; Hypergrid configuration. Otherwise, ignore.

    ;# {GatekeeperURI} {Hypergrid} {The URL of the gatekeeper of this world} {}
    ;; If this is a standalone world, this is the address of this instance.
    ;; If this is a grided simulator, this is the address of the external robust server
    ;; that runs the Gatekeeper service.
    ;; For example http://myworld.com:9000 or http://myworld.com:8002
    ;; This is a default that can be overwritten in some sections.
    GatekeeperURI = "${Const|BaseURL}:${Const|PublicPort}"

    ;# {GatekeeperURIAlias} {Hypergrid} {alternative hostnames (FQDN) or IPs of the gatekeeper of this world and port (default 80 or 443 if entry starts with https://)} {}
    ;; comma separated list,
    ;; this is to allow this world to identify this entries also as references to itself
    ;; entries can be unsecure url (host:port) if using ssl, direct login url if diferent, old grid url, etc
    ; GatekeeperURIAlias = myoldname.something.org, 127.0.0.1,127.0.0.1:8043

    ;# {HomeURI} {Hypergrid} {The Home URL of this world} {}
    ;; If this is a standalone world, this is the address of this instance.
    ;; If this is a grided simulator, this is the address of the external robust server that
    ;; runs the UserAgentsService.
    ;; For example http://myworld.com:9000 or http://myworld.com:8002
    ;; This is a default that can be overwritten in some sections.
    HomeURI = "${Const|BaseURL}:${Const|PublicPort}"

    ;# {HomeURIAlias} {Hypergrid} {alternative hostnames (FQDN), or IPs of the home service of this world and port (default 80 or 443)} {}
    ;; comma separated list, 
    ;; see GatekeeperURIAlias
    ; HomeURIAlias = myoldname.something.org, 127.0.0.1,127.0.0.1:8043	

[Modules]
    ;; Asset cache module.
    ;; Warning this is required for several region features

    AssetCaching = "FlotsamAssetCache"
    Include-FlotsamCache = "config-include/FlotsamCache.ini"

    ;; Authorization is not on by default, as it depends on external php
    ;AuthorizationServices = "LocalAuthorizationServicesConnector"

[AssetService]
    DefaultAssetLoader = "OpenSim.Framework.AssetLoader.Filesystem.dll"
    AssetLoaderArgs = "assets/AssetSets.xml"

[GridService]
    ;; For in-memory region storage (default)
    StorageProvider = "OpenSim.Data.Null.dll:NullRegionData"
    ;;--- For MySql region storage (alternative)
    ;StorageProvider = "OpenSim.Data.MySQL.dll:MySqlRegionData"

    ;; Directory for map tile images of remote regions
    ; MapTileDirectory = "./maptiles"

    ;; Next, we can specify properties of regions, including default and fallback regions
    ;; The syntax is: Region_<RegionName> = "<flags>"
    ;; where <flags> can be DefaultRegion, FallbackRegion, NoDirectLogin, Persistent, LockedOut
    ;;
    ;; DefaultRegion    If a local login cannot be placed in the required region (e.g. home region does not exist, avatar is not allowed entry, etc.)
    ;;                  then this region becomes the destination.  Only the first online default region will be used.  If no DefaultHGRegion
    ;;                  is specified then this will also be used as the region for hypergrid connections that require it (commonly because they have not specified
    ;;                  an explicit region.
    ;;
    ;; DefaultHGRegion  If an avatar connecting via the hypergrid does not specify a region, then they are placed here.  Only the first online
    ;;                  region will be used.
    ;;
    ;; FallbackRegion   If the DefaultRegion is not available for a local login, then any FallbackRegions are tried instead.  These are tried in the
    ;;                  order specified.  This only applies to local logins at this time, not Hypergrid connections.
    ;;
    ;; NoDirectLogin    A hypergrid user cannot directly connect to this region.  This does not apply to local logins.
    ;;
    ;; Persistent       When the simulator is shutdown, the region is signalled as offline but left registered on the grid.
    ;;
    ;; For example:
    Region_My_World = "DefaultRegion, DefaultHGRegion, FallbackRegion"

    ;; Allow supporting viewers to export content
    ;; Set to false to prevent export
    ExportSupported = true

[LibraryModule]
    ; Set this if you want to change the name of the OpenSim Library
    LibraryName = "My World's Library"

[LoginService]
    WelcomeMessage = "Welcome to My World!\nLogin: opensim opensim\nPassword: opensim123"

    SRV_HomeURI = "${Hypergrid|HomeURI}"
    SRV_InventoryServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_AssetServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_ProfileServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_FriendsServerURI = "${Const|BaseURL}:${Const|PublicPort}"
    SRV_IMServerURI = "${Const|BaseURL}:${Const|PublicPort}"

    ;; For Viewer 2
    MapTileURL = "${Const|BaseURL}:${Const|PublicPort}/"

    ; Url to search service
    ; SearchURL = "${Const|BaseURL}:${Const|PublicPort}";

    ; For V3 destination guide
    ; DestinationGuide = "${Const|BaseURL}/guide"

    ; The minimum user level required for a user to be able to login.  0 by default
    ; If you disable a particular user's account then you can set their login level below this number.
    ; You can also change this level from the console though these changes will not be persisted.
    ; MinLoginLevel = 0

    ;; Ask co-operative viewers to use a different currency name
    ;Currency = ""

    ;; Set minimum fee to publish classified
    ; ClassifiedFee = 0

    ;; If the region requested at login is not found and there are no default or fallback regions
    ;; online or defined in section [GridService], try to send user to any region online
    ;; this similar to legacy (was disabled on 0.9.2.0)
    ;; you should set this to false and define  regions with Default and possible Fallback flags
    ;; With this option set to true, users maybe sent to regions they where not supposed to be, or even know about
    ;AllowLoginFallbackToAnyRegion = true

    ; Basic Login Service Dos Protection Tweaks

    ;; Some Grids/Users use a transparent proxy that makes use of the X-Forwarded-For HTTP Header, If you do, set this to true
    ;; If you set this to true and you don't have a transparent proxy, it may allow attackers to put random things in the X-Forwarded-For header to
    ;;     get around this basic DOS protection.
    ; DOSAllowXForwardedForHeader = false

    ;; The protector adds up requests during this rolling period of time, default 10 seconds
    ; DOSRequestTimeFrameMS = 10000
    ;;
    ;; The amount of requests in the above timeframe from the same endpoint that triggers protection
    ; DOSMaxRequestsInTimeFrame = 5
    ;;
    ;; The amount of time that a specific endpoint is blocked.    Default 2 minutes.
    ; DOSForgiveClientAfterMS = 120000

    ;; To turn off basic dos protection, set the DOSMaxRequestsInTimeFrame to 0.

[GridInfoService]
    ; These settings are used to return information on a get_grid_info call.
    ; Client launcher scripts and third-party clients make use of this to
    ; autoconfigure the client and to provide a nice user experience. If you
    ; want to facilitate that, you should configure the settings here according
    ; to your grid or standalone setup.
    ;
    ; See http://opensimulator.org/wiki/GridInfo

    ; login uri: for grid this is the login server URI
    login = ${Const|BaseURL}:${Const|PublicPort}/

    ; long grid name: the long name of your grid
    gridname = "My World"

    ; short grid name: the short name of your grid
    gridnick = "myworld"

    ; login page: optional: if it exists it will be used to tell the client to use
    ; this as splash page. May also be served from an external web server, e.g. for
    ; information on a standalone
    ;welcome = ${Const|BaseURL}/welcome

    ; helper uri: optional: if it exists it will be used to tell the client to use
    ;                       this for all economy related things
    ;economy = ${Const|BaseURL}/economy

    ; web page of grid: optional: page providing further information about your grid
    about = ${Const|BaseURL}/about

    ; account creation: optional: page providing further information about obtaining
    ;                             a user account on your grid
    register = ${Const|BaseURL}/register

    ; help: optional: page providing further assistance for users of your grid
    help = ${Const|BaseURL}/help

    ; password help: optional: page providing password assistance for users of your grid
    password = ${Const|BaseURL}/password

    ; HG address of the gatekeeper, if you have one
    ; this is the entry point for all the regions of the world
    gatekeeper = ${Const|BaseURL}:${Const|PublicPort}/

    ; HG user domain, if you have one
    ; this is the entry point for all user-related HG services
    uas = ${Const|BaseURL}:${Const|PublicPort}/

    ;; a http page for grid status
    ;GridStatus = ${Const|BaseURL}:${Const|PublicPort}/GridStatus
    ;; a RSS page for grid status
    ;GridStatusRSS = ${Const|BaseURL}:${Const|PublicPort}/GridStatusRSS

[EntityTransfer]
    ;; User level from which local users are allowed to HG teleport. Default 0 (all users)
    ;LevelHGTeleport = 0

    ;; Are local users restricted from taking their appearance abroad?
    ;; Default is no restrictions
    ;RestrictAppearanceAbroad = false

    ;; If appearance is restricted, which accounts' appearances are allowed to be exported?
    ;; Comma-separated list of account names
    AccountForAppearance = "opensim opensim"

[UserProfilesService]
    ;; To use, set Enabled to true then configure for your site...
    Enabled = true
    LocalServiceModule = "OpenSim.Services.UserProfilesService.dll:UserProfilesService"

    ;; Configure this for separate databse
    ; ConnectionString = "Data Source=localhost;Database=opensim;User ID=opensim;Password=***;Old Guids=true;"
    ; Realm = UserProfiles

    UserAccountService = OpenSim.Services.UserAccountService.dll:UserAccountService
    AuthenticationServiceModule = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"

[Messaging]
    ;; For standalones, this is the storage dll.
    ;StorageProvider = "OpenSim.Data.SQLite.dll"

    ; Message Transfer Module Config
    MessageTransferModule = "MessageTransferModule"
    LureModule = "LureModule"

    ; OfflineIM Module Config - disabled for now
    ;OfflineMessageModule = "Offline Message Module V2"
    ; Without this uncommented, your offline IMs will be lost when you restart OpenSim.
    ;OfflineMessageURL = "${Const|PrivURL}:${Const|PrivatePort}"
    ; For standalones, this is the storage dll.
    ;StorageProvider = "OpenSim.Data.SQLite.dll"

[Groups]
    Enabled = true

    ;# {Module} {Enabled:true} {Groups module to use? (Use GroupsModule to use Flotsam)} {Default "Groups Module V2"} Default
    Module = "Groups Module V2"

    ;# {StorageProvider} {Module:Groups Module V2} {The DLL that provides the storage for V2} {OpenSim.Data.MySQL.dll}
    StorageProvider = "Diva.Data.SQLite.dll"

    ;# {ServicesConnectorModule} {Module:Groups Module V2} {Service connector to use for groups} {"Groups Local Service Connector" "Groups Remote Service Connector" "Groups HG Service Connector"} 
    ;; Note that the quotes "" around the words are important!
    ServicesConnectorModule = "Groups Local Service Connector"

    ;# {LocalService} {ServicesConnectorModule:Groups HG Service Connector} {Is the group service in this process or elsewhere?} {local remote} local
    ;; Used for V2 in HG only. If standalone, set this to local; if grided sim, set this to remote
    LocalService = local

    ;# {SecretKey} {ServicesConnectorModule:Groups Remote Service Connector} {Secret key between sim and remote group service} {} ""
    ;; Used for V2 in Remote only.
    ;SecretKey = ""

    ;# {GroupsServerURI} {Module:GroupsModule (ServicesConnectorModule:Groups Remote Service Connector or (ServicesConnectorModule:Groups HG Service Connector and LocalService:remote))} {Groups Server URI} {}
    ;; URI for the groups services of this grid
    ;; e.g. http://yourxmlrpcserver.com/xmlrpc.php for Flotsam XmlRpc
    ;; or ${Const|PrivURL}:${Const|PrivatePort} for robust, V2
    ;; Leave it commented for standalones, V2
    ;GroupsServerURI = ""

    ;# {HomeURI} {ServicesConnectorModule:Groups HG Service Connector} {What's the home address of this world?} {}
    ;; http://mygridserver.com:9000 or http://mygridserver.com:8002
    ;; If you have this set in [Startup] or [Hypergrid], leave it commented
    ;HomeURI = ""

    ;# {MessagingEnabled} {Module:GroupsModule Module:Groups Module V2} {Is groups messaging enabled?} {true false} true
    MessagingEnabled = true

    ;# {MessagingModule} {MessagingEnabled:true} {Module to use for groups messaging} {GroupsMessagingModule "Groups Messaging Module V2"} GroupsMessagingModule
    MessagingModule = "Groups Messaging Module V2"

    ;# {NoticesEnabled} {Module:GroupsModule Module:Groups Module V2} {Enable group notices?} {true false} true
    ;; Enable Group Notices
    NoticesEnabled = true

    ;# {MessageOnlineUsersOnly} {Module:GroupsModule Module} {Message online users only?} {true false} false
    ; Experimental option to only message online users rather than all users
    ; Should make large groups with few online members messaging faster, as the expense of more calls to presence service
    ; Applies Flotsam Group only. V2 has this always on, no other option
    ;MessageOnlineUsersOnly = false

    ;## {DebugEnabled} {Module:GroupsModule Module:Groups Module V2} {Enable groups module debug?} {true false} false
    ;DebugEnabled = false

[WifiService]
    Enabled = true
    GridName = "My World"
    LoginURL = "${Const|BaseURL}:${Const|PublicPort}"
    WebAddress = "${Const|BaseURL}:${Const|PublicPort}"

    ;; The Wifi Administrator account
    AdminFirst = "opensim"
    AdminLast = "opensim"
    AdminEmail = "admin@opensim.local"

    ;; Do you want to be able to control grid registrations?
    AccountConfirmationRequired = false

    ;; Default avatars for new account registration
    ;; Syntax: AvatarAccount_<AvatarType> = "<FirstName> <LastName>"
    ;;         (replace spaces in <AvatarType> with underscore)
    ;; Appearance and attachments are copied from avatar <FirstName> <LastName>.
    AvatarAccount_Female = "Female Avatar"
    AvatarAccount_Male = "Male Avatar"
    AvatarAccount_Neutral = "Neutral Avatar"

    ;; Preselection for default avatar in new account registration
    AvatarPreselection = "Neutral"

    ;; Home location for new accounts
    ;; If empty or not set, then the selected default avatar's home location is used.
    ; HomeLocation = "<RegionName>/<X>/<Y>/<Z>"

    ;; Accounts with this or a higher user level are able to create links to
    ;; hypergrid regions. Other users are only able to view existing hyperlinks.
    HyperlinkServiceUserLevel = 50

    ;; Time interval in seconds for updating statistics data for variables like
    ;; UsersInworld, UsersTotal, and RegionsTotal.
    ;; Default value 0 disables data updates.
    StatisticsUpdateInterval = 60
    ;; Period in days for computing the number of active users
    StatisticsActiveUsersPeriod = 30

;; Include our specific world configuration
[Includes]
    Include-Common = "config-include/MyWorld.ini"

    ;; Default avatars for new account registration
    ;; Syntax: AvatarAccount_<AvatarType> = "<FirstName> <LastName>"
    ;;         (replace spaces in <AvatarType> with underscore)
    ;; Appearance and attachments are copied from avatar <FirstName> <LastName>.
    AvatarAccount_Female = "Female Avatar"
    AvatarAccount_Male = "Male Avatar"
    AvatarAccount_Neutral = "Neutral Avatar"

    ;; Preselection for default avatar in new account registration
    AvatarPreselection = "Neutral"

    ;; Home location for new accounts
    ;; If empty or not set, then the selected default avatar's home location is used.
    ; HomeLocation = "<RegionName>/<X>/<Y>/<Z>"

    ;; Accounts with this or a higher user level are able to create links to
    ;; hypergrid regions. Other users are only able to view existing hyperlinks.
    HyperlinkServiceUserLevel = 50

    ;; Time interval in seconds for updating statistics data for variables like
    ;; UsersInworld, UsersTotal, and RegionsTotal.
    ;; Default value 0 disables data updates.
    StatisticsUpdateInterval = 60
    ;; Period in days for computing the number of active users
    StatisticsActiveUsersPeriod = 30

; Includes MyWorld.ini which has our specific world configuration
[Includes]
    Include-Common = "config-include/MyWorld.ini"