[My World]
	Location = 1000,1000
	RegionUUID = 11111111-2222-3333-4444-555555555555
	SizeX = 512
	SizeY = 512
	SizeZ = 512
	InternalAddress = 0.0.0.0
	InternalPort = 9010
	ResolveAddress = False
	ExternalHostName = 127.0.0.1
	MaptileStaticUUID = 11111111-2222-3333-4444-555555555555
	InternalAddress = 0.0.0.0
	AllowAlternatePorts = False
	;NonPhysicalPrimMax = 512
	;PhysicalPrimMax = 128
	;ClampPrimSize = false
	;MaxPrimsPerUser = -1
	;ScopeID = 11111111-2222-3333-4444-555555555555
	;RegionType = Mainland
	;RenderMinHeight = -1
	;RenderMaxHeight = 100
	;MapImageModule = Warp3DImageModule
	;TextureOnMapTile = true
	;DrawPrimOnMapTile = true
	;GenerateMaptiles = true
	;MaptileRefresh = 0
	;MaptileStaticFile = path/to/SomeFile.png
	;MasterAvatarFirstName = John
	;MasterAvatarLastName = Doe
	;MasterAvatarSandboxPassword = passwd